default:
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind

variables:
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest

stages:
  - build
  - test
  - release
  - deploy

before_script:
  - docker info
  - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin

build:
  stage: build
  script:
    - docker-compose -f docker-compose.yml build
    - docker-compose -f docker-compose.yml push
  only:
    - master
    - main
    - tags

unit-test-job:
  stage: test
  script:
    - docker-compose -f docker-compose.yml -f docker-compose.test.yml build --no-cache
    - docker-compose -f docker-compose.yml -f docker-compose.test.yml up -d db
    - docker-compose -f docker-compose.yml -f docker-compose.test.yml run backend /bin/sh -c "export PATH=\$PATH:/home/app/.local/bin && pytest --junitxml=/app/test-results.xml tests"
  artifacts:
    when: always
    reports:
      junit: services/backend/test-results.xml
    paths:
      - services/backend/test-results.xml
  after_script:
    - docker-compose -f docker-compose.yml -f docker-compose.test.yml down -v --remove-orphans

lint-test-job:
  stage: test
  script:
    - docker-compose -f docker-compose.yml run backend /home/app/.local/bin/flake8 /app
  after_script:
    - docker-compose -f docker-compose.yml down

release-image:
  stage: release
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE
  only:
    - master
    - main
    - tags

deploy-job:
  stage: deploy
  environment: production
  script:
    - docker-compose -f docker-compose.yml up -d
  only:
    - master
    - main
