version: "3.8"

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test_db

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - .:/home/app
    environment:
      DATABASE_URL: postgres://user:password@db:5432/test_db
    entrypoint: ["/bin/sh", "-c"]
    command: |
      export PATH=$PATH:/home/app/.local/bin && 
      flake8 /home/app && 
      pytest tests
