version: "3.8"

services:
  backend:
    container_name: iu-project-software-engineering-backend-test-1
    build:
      context: ./services/backend
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./services/backend:/app
    environment:
      DATABASE_URL: postgres://user:password@db:5432/test_db
    entrypoint: ["/bin/sh", "-c"]
    command: |
      export PATH=$PATH:/home/app/.local/bin && 
      pytest tests

  db:
    container_name: iu-project-software-engineering-db-test-1
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
