version: '3.8'

services:
  nuxt3-shadcn:
    container_name: my-nuxt3-app
    build: 
      context: ./services/nuxt3-shadcn
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - './nuxt3-scadcn:/app'  # Mount the entire application directory
      - '/app/node_modules'    # Ensure node_modules persistence
    environment:
      - NODE_ENV=production
    networks:
      - my-network
  
  pgadmin:
    container_name: my-pgadmin
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=name@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    restart: always

  frontend:
    container_name: iu-project-software-engineering-frontend-1
    build: ./services/frontend
    volumes:
      - './services/frontend:/app'
      - '/app/node_modules'
    ports:
      - 8080:8080
    networks:
      - my-network

  backend:
    container_name: iu-project-software-engineering-backend-1
    build: ./services/backend
    ports:
      - 8000:8000
    volumes:
      - ./services/backend:/app
    command: /home/app/.local/bin/uvicorn main:app --reload --host 0.0.0.0 --port 8000
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - my-network

  db:
    container_name: iu-project-software-engineering-db-1
    image: postgres:16.2
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=hoppybrew_db
    ports:
      - "5432:5432"
    restart: always
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  postgres_data:
