version: "3.8"

services:
  backend:
    container_name: iu-project-software-engineering-backend-1
    build:
      context: ./services/backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./services/backend:/app
    command: /home/app/.local/bin/uvicorn main:app --reload --host 0.0.0.0 --port 8000
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - my-network

  db:
    container_name: iu-project-software-engineering-db-1
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=hoppybrew_db
    ports:
      - "5432:5432"
    restart: always
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  postgres_data:
