@startuml

class "Boil_Temperature" as Boil_Temperature {
    + id : uuid
    --
    altitude_adjustment : boolean
    altitude : decimal
    boil_temp : decimal
    cooling_shrinkage : decimal
}

EquipmentProfile -- Boil_Temperature
@enduml