@startuml
class "Efficiency" as Efficiency {
    + id : uuid
    --
    brewhouse_efficiency : decimal
    mash_efficiency : decimal
    calc_mash_efficiency : boolean
}

EquipmentProfile -- Efficiency
@enduml