@startuml
class "Sparge_Water_limit" as Sparge_Water_limit {
    + id : int
    --
    min_sparge_volume : decimal /' EngUnit: L, Min Sparge Volume '/
    max_sparge_volume : decimal /' EngUnit: L, Max Sparge Volume '/
    overflow_target : decimal /' EngUnit: L, Overflow Target '/
}

EquipmentProfile -- Sparge_Water_limit
@enduml