@startuml
class "Strike_Water_Temp" as Strike_Water_Temp {
    + id : uuid
    --
    calc_strike_water_temp : boolean
    mash_tune_heat_capacity : decimal
    room_temp : decimal
    grain_temp : decimal
}

EquipmentProfile -- Strike_Water_Temp
@enduml