@startuml

class "WaterProfile" as WaterProfile {
    + id : uuid
    --
    name : string
    water_profile_type : WaterProfileType
    water_ph : decimal /' EngUnit: pH, Water pH '/
    cation : Cation
    anion : Anion
}

@enduml