from pydantic import BaseModel
from typing import Optional, List


class HopBase(BaseModel):
    """
    Description:
    This class represents the Hops table in the database.

    Use cases:
    - Validate the data of a new Hops object
    - Validate the data of a Hops object to be updated

    Notes:
    - The id field is not included in the base model because it is generated by the database
    """

    name: str
    version: Optional[int]
    origin: Optional[str]
    alpha: Optional[int]
    amount: Optional[int]
    use: Optional[str]
    time: Optional[int]
    notes: Optional[str]
    type: Optional[str]
    form: Optional[str]
    beta: Optional[int]
    hsi: Optional[int]
    display_amount: Optional[str]
    inventory: Optional[int]
    display_time: Optional[str]
