from pydantic import BaseModel
from .hops import HopBase
from typing import Optional, List


class RecipeBase(BaseModel):
    """
    Description:
    This class represents the Recipe table in the database.

    Use cases:
    - Validate the data of a new Recipe object
    - Validate the data of a Recipe object to be updated

    Notes:
    - The id field is not included in the base model because it is generated by the database
    - The hops field is a list of Hops objects

    """

    name: str
    version: int
    type: Optional[str]
    brewer: Optional[str]
    asst_brewer: Optional[str]
    batch_size: Optional[float]
    boil_size: Optional[float]
    boil_time: Optional[int]
    efficiency: Optional[float]
    # mash: Optional[str]
    notes: Optional[str]
    taste_notes: Optional[str]
    taste_rating: Optional[int]
    og: Optional[float]
    fg: Optional[float]
    fermentation_stages: Optional[int]
    primary_age: Optional[int]
    primary_temp: Optional[float]
    secondary_age: Optional[int]
    secondary_temp: Optional[float]
    tertiary_age: Optional[int]
    tertiary_temp: Optional[float]
    age: Optional[int]
    age_temp: Optional[float]
    carbonation_used: Optional[str]
    # carbonation_date: Optional[date]
    est_og: Optional[float]
    est_fg: Optional[float]
    est_color: Optional[float]
    ibu: Optional[float]
    ibu_method: Optional[str]
    est_abv: Optional[float]
    abv: Optional[float]
    actual_efficiency: Optional[float]
    calories: Optional[float]
    display_batch_size: Optional[str]
    display_boil_size: Optional[str]
    display_og: Optional[str]
    display_fg: Optional[str]
    display_primary_temp: Optional[str]
    display_secondary_temp: Optional[str]
    display_tertiary_temp: Optional[str]
    display_age_temp: Optional[str]

    # hop(s) indicates it is a list containing individual hop objects
    hops: Optional[List[HopBase]] = None
