---
title: "|   Software Engineering\n|   < DLMCSPSE01 />\n|\n|   Project: **HoppyBrew**\n|\n|\n| **Concept Phase**\n|\n|\n|   *International University of Applyied Sciences*\n|\n|\n"
author: |
  |   Written by
  |   Asbjorn Bordoy
date: "|   On the\n|   18-Mar-2024\n|\n|\n|\n|   **Revision 1.0**\n|\n|\n"
pagetitle: "Programming with Python"
abstract: |
  
  | **Abstract**: The project aims to develop a comprehensive Beer Brewing Recipe Manager system, catering to brewing enthusiasts and homebrewers. This system facilitates the management of brewing processes and associated data through intuitive interfaces and robust functionalities. Users can create, share, and manage beer recipes, customize water and equipment profiles, schedule brewing sessions, monitor fermentation in real-time, generate reports, and more. The system ensures a seamless user experience by integrating with external devices like ISpindel for data collection and leveraging a database for secure storage and retrieval of brewing-related information. With an emphasis on user-friendly design and versatile features, the Beer Brewing Recipe Manager fosters innovation and tradition in the art of homebrewing.

knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = "build") })
output:
  pdf_document:
    latex_engine: pdflatex
    number_sections: yes
    fig_caption: yes
    pandoc_args: ["--highlight-style=zenburn"]
    includes:  
      in_header: preamble.tex
  github_document :
  html_document:
    df_print: paged
    always_allow_html: yes
    toc: yes
    number_sections: yes
    toc_float: tru
  rmdformats::downcute:
    highlight: tango
    lightbox: true
    self_contained: true
    theme: readable
    code_folding: show
    toc_float: true
  md_document:
    variant: gfm
bibliography: ../bibliography.bib
link-citations: yes
urlcolor: blue
papersize: a4
fontsize: 12pt
geometry: margin=1in
fontfamily: charter
header-includes:
- \setlength\parindent{24pt}
linkReferences: yes
---

```{=tex}
\let\oldsection\section
\maketitle
\thispagestyle{empty}
\clearpage
```
```{=tex}
\tableofcontents
\pagenumbering{roman}
\clearpage
```
```{=tex}
\listoftables
\clearpage
```
```{=tex}
\listoffigures
\clearpage
```
```{=tex}
\pagenumbering{arabic}
\setcounter{page}{1}
```

```{=html}
<style>
body {
text-align: justify}
</style>
```

```{r, include=FALSE}
options(tinytex.verbose = TRUE)
```



```{r child = './chapters/01_introduction_and_goals.Rmd'}
```

```{r child = './chapters/02_architecture_constraints.Rmd'}
```

```{r child = './chapters/03_system_scope_and_context.Rmd'}
```

```{r child = './chapters/04_solution_strategy.Rmd'}
```

```{r child = './chapters/05_building_block_view.Rmd'}
```

```{r child = './chapters/06_runtime_view.Rmd'}
```

```{r child = './chapters/07_deployment_view.Rmd'}
```

```{r child = './chapters/08_concepts.Rmd'}
```

```{r child = './chapters/09_architecture_decisions.Rmd'}
```

```{r child = './chapters/10_quality_requirements.Rmd'}
```

```{r child = './chapters/11_technical_risks.Rmd'}
```

```{r child = './chapters/12_glossary.Rmd'}
```
