# File:  docker-compose.yml
# Author:  Asbjorn Bordoy
# Date:  2024-apr-05
# Description:  Docker compose file for the HoppyBrew application.

# Usage:  docker-compose up

version: "3.8"

services:
  hoppybrew-db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    hostname: hoppybrew-db
    ports:
      - "5432:5432"

  hoppybrew-app:
    build:
      context: ../
      dockerfile: docker/Dockerfile

    environment:
      NAME: HoppyBrew
      DATABASE_HOST: hoppybrew-db
      DATABASE_PORT: 5432
      DATABASE_NAME: hoppybrew_db
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
    ports:
      - "8000:8000"
    depends_on:
      - hoppybrew-db