
# Dockerfile
TODO: Check version of alpine
FROM alpine:3.17 as builder

# Install python3 and pip3
RUN apk add --no-cache python3 py3-pip libpq postgresql-client curl

# Add user dbs
RUN adduser -D dbs

# Switch to user dbs
USER dbs

# Set working directory
WORKDIR /home/dbs

# Copy files
COPY . .

# Install requirements
RUN pip3 install -r requirements.txt --no-cache-dir

# Expose port 8000
EXPOSE 8000

# Run uvicorn
CMD /home/dbs/.local/bin/uvicorn dbs_assignment.__main__:app --reload --host 0.0.0.0


