@startuml

!include documents/docs/plantuml/ERD/ingredients/Hop.puml
!include documents/docs/plantuml/ERD/ingredients/Misc.puml
!include documents/docs/plantuml/ERD/ingredients/Yeast.puml
!include documents/docs/plantuml/ERD/ingredients/Fermentable/Adjunct.puml 
!include documents/docs/plantuml/ERD/ingredients/Fermentable/DryExtract.puml 
'!include documents/docs/plantuml/ERD/ingredients/Fermentable/Fermentable_Category.puml 
!include documents/docs/plantuml/ERD/ingredients/Fermentable/Grain.puml 
!include documents/docs/plantuml/ERD/ingredients/Fermentable/LiquidExtract.puml 
!include documents/docs/plantuml/ERD/ingredients/Fermentable/Other.puml 
!include documents/docs/plantuml/ERD/ingredients/Fermentable/Sugar.puml

!include documents/docs/plantuml/ERD/ingredients/Fermentable.puml

class "Inventory" as Inventory {
    + id : uuid
    --
    ..General..

    ..Inventory..
    quantity : decimal
    cost : decimal
    ==Relations==
    {static} hop_id : uuid
    {static} yeast_id : uuid
    {static} misc_id : uuid
    {static} fermentable_id : uuid
    {static} adjunct_id : uuid
    {static} dry_extract_id : uuid
    {static} liquid_extract_id : uuid
    {static} sugar_id : uuid
    {static} other_id : uuid
}

Inventory --{ Grain
Inventory --{ Sugar 
Inventory --{ LiquidExtract 
Inventory --{ DryExtract 
Inventory --{ Adjunct 
Inventory --{ Other 
Inventory --{ Hops
Inventory --{ Yeast
Inventory --{ Misc
@enduml