
@startuml
!include documents/docs/plantuml/ERD/ingredients/Fermentable.puml
!include documents/docs/plantuml/ERD/ingredients/Hop.puml
!include documents/docs/plantuml/ERD/ingredients/Misc.puml
!include documents/docs/plantuml/ERD/ingredients/Yeast.puml

!include documents/docs/plantuml/ERD/Profiles/EquipmentProfile.puml
!include documents/docs/plantuml/ERD/Profiles/FermentationProfile.puml
!include documents/docs/plantuml/ERD/Profiles/MashProfile.puml
!include documents/docs/plantuml/ERD/Profiles/WaterProfile.puml

class "Recepie" as Recepie {
    + id : uuid
    --
    ..General..
    name : string
    version : int
    author : string
    asst_brewer : string
    type : RecipeType
    ..Properties..
    notes : string
}

Enum "RecipeType" {
    All_Grain
    Extract
    Partial_Mash
    Cider
    Mead
    Wine
    Kombucha
    Soda
    Other
}

Recepie -- RecipeType
Recepie -- EquipmentProfile
Recepie -- TargetStyle
Recepie --{ Fermentable
Recepie --{ Hops
Recepie --{ Misc
Recepie --{ Yeast
Recepie -- MashProfile
Recepie -- FermentationProfile
Recepie -- WaterProfile
@enduml