@startuml
class "MashStep" as MashStep {
    + id : uuid
    --
    name : string                           /' Mash Step Name '/
    type : MashStepType                     /' MashStepType id '/
    temperature : decimal                   /' EngUnit: C, Temperature '/
    time : decimal                          /' EngUnit: min, Time '/
    ramp_time : decimal                     /' EngUnit: min, Ramp Time '/
}

MashProfile --{ MashStep
@enduml