@startuml

title Technical Context Diagram

actor user as "Operator"
boundary WebServer as "Web Server"
control AppServer as "Application Server"
entity Database as "Database"
entity ISpindel as "iSpindel"


user -> WebServer : HTTP Request
WebServer -> AppServer : HTTP Request
AppServer -> Database : SQL Query
Database -> AppServer : SQL Response
AppServer -> WebServer : HTTP Response
WebServer -> user : HTTP Response

ISpindel -> AppServer : HTTP Request
AppServer -> ISpindel : HTTP Response

@enduml
