@startuml 04-white-box-overall-system

title White Box Overall System

interface " " as I01
interface " " as I02

component "Client Browser" as ClientBrowser
component "ISpindel" as ISpindel

cloud "Internet" {
    component "Cloudflare" as cloudflare
}

ClientBrowser --( I01 : Uses
I01 - cloudflare 

ISpindel --( I02 : Transmits Data
I02 - cloudflare 




rectangle "Unraid Server" {
    node "Docker Engine" {
        component "Cloudflare" as CloudflareTunnel

        cloudflare <|..|> CloudflareTunnel : <<TUNNEL>>

        node "App Container" as Application_Container {
            component "HoppyBrew" as HoppyBrew
            component "Psycopg\ndb-adapter" as db_adapter
            component "FastAPI" as api
            component "uvicorn" as uvicorn
            component "endpoints" as endpoints
            component "APIRouter" as APIRouter

            api - HoppyBrew : Uses
            HoppyBrew -- db_adapter : Uses
            api -- uvicorn  : Runs
            api -- endpoints  : Uses
            api -- APIRouter  : Uses
        }

        interface " " as I03
        CloudflareTunnel --( I03 : Uses
        I03 -- api


        node "PostgreSQL Container" {
            component "PostgreSQL" as db
        }

        interface " " as I04
        db_adapter --( I04 : Uses
        I04 -- db
    }
}
@enduml