@startuml


component "Client Browser" {
    portout "Port:443" as Client_Port80
}

component "ISpindel" {
    portout "Port:9501" as ISpindel_Port80
}

cloud "Internet" {
    component "Cloudflare" as cloudflare
}

ISpindel_Port80 -- cloudflare
Client_Port80 -- cloudflare

rectangle "Unraid Server" {
    node "Docker Engine" {
        component "Cloudflare" as tunnel{
            portout "Port 443" as CloudFlare_portout443
        }
        cloudflare <|..|> tunnel : <<TUNNEL>>

        node "App Container" as Application_Container {
            component "HoppyBrew" as HoppyBrew
            component "Psycopg\ndb-adapter" as db_adapter
            component "FastAPI" as api
            component "uvicorn" as uvicorn
            component "endpoints" as endpoints
            component "APIRouter" as APIRouter

            portin "Port 443" as HoppyBrew_portin443
            portout "Port 5432" as HoppyBrew_portout5432

            HoppyBrew_portin443 - api : Listens On

            api - HoppyBrew : Uses
            HoppyBrew -- db_adapter : Uses
            api -- uvicorn  : Runs
            api -- endpoints  : Uses
            api -- APIRouter  : Uses
            
            db_adapter - HoppyBrew_portout5432 : Listens On

        }
        CloudFlare_portout443 -- HoppyBrew_portin443  : Connects To

        node "PostgreSQL Container" {
            component "PostgreSQL" as db
            
            portin "Port 5432" as Postgres_port5432

            Postgres_port5432 -- db : Listens On
        }

        HoppyBrew_portout5432 -- Postgres_port5432 : Connects To
        
    }
}

@enduml
