@startuml

left to right direction

rectangle "Primary Actors" {
    actor Administrator as Admin
    actor Brewer as Brew
    actor "{abstract}\nSuper Actor" as SuperActor

}

rectangle "Secondary actors"{
    actor Database as DB
    actor ISpindel as ISpindel
}

rectangle "Beer Brewing Recipe Manager" {

    rectangle "Users" {
        usecase (Manage own\nuser account) as ManageOwnUser
        usecase (Manage\nUser accounts\n---\nCRUD) as ManageUserAccounts
        ManageUserAccounts .> ManageOwnUser : include
    }

    rectangle "Recipes" {
        usecase (Manage\nrecipes) as ManageRecipes
        usecase (Beer Style) as SelectedRecipeBeerStyle
        ManageRecipes .> SelectedRecipeBeerStyle : <<extend>>
    }

    rectangle "Batch" {
        usecase (Manage\nbatches) as ManageBatches
        usecase (Beer Style) as SelectedBatchBeerStyle
        usecase (Monitor\nbatch) as MonitorBatch
        ManageBatches .> SelectedBatchBeerStyle : <<extend>>
        
    }

    rectangle "Inventory" {
        usecase (Manage\ninventory) as ManageInventory
    }

    rectangle "Equipment" {
        usecase (Manage Equipment\nprofiles) as SelectEquipmentProfile
    }

    rectangle "Beer Style" {
        usecase (Retrieve Beer Style\nrecommendation) as BeerStyleRecommendation
    }



}

Admin --|> SuperActor
Brew --|> SuperActor

Admin --> ManageUserAccounts
SuperActor --> ManageOwnUser
SuperActor --> BeerStyleRecommendation

BeerStyleRecommendation .> SelectedRecipeBeerStyle : <<include>>
BeerStyleRecommendation .> SelectedBatchBeerStyle : <<include>>

ManageBatches .> ManageInventory : <<include>>

SuperActor --> ManageRecipes
SuperActor --> ManageInventory
SuperActor --> ManageBatches


ManageRecipes .> ManageBatches : include
ManageRecipes --> SelectEquipmentProfile

ManageInventory --> DB
ISpindel --> MonitorBatch


@enduml