@startuml

left to right direction
skinparam packageStyle rectangle

actor User as U
rectangle HoppyBrew {
  usecase "Create Account" as UC1
  usecase "Login" as UC2
  usecase "Logout" as UC3
  usecase "View Recipe" as UC4
  usecase "Search Recipe" as UC5
  usecase "Create Recipe" as UC6
  usecase "Edit Recipe" as UC7
  usecase "Delete Recipe" as UC8
  usecase "Track Fermentation" as UC9
  usecase "Manage Inventory" as UC10
  usecase "Generate Shopping List" as UC11
}

U --> UC1
U --> UC2
U --> UC3
U --> UC4
U --> UC5
U --> UC6
U --> UC7
U --> UC8
U --> UC9
U --> UC10
U --> UC11

@enduml
